import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {transform} from 'lightningcss';
import {fileURLToPath} from 'node:url';
import {sfh,canonicalKey} from './build-lmo.mjs';
import {catalog,hashKey,validateCatalog} from './catalog.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const controls=read('htdocs/luci-static/nova/controls.css');
for(const name of ['cascade','components','visual','controls','persian','languages','telemetry','firewall']){
 const parsed=transform({filename:name+'.css',code:Buffer.from(read('htdocs/luci-static/nova/'+name+'.css')),errorRecovery:false});
 assert.equal(parsed.warnings.length,0,name+' CSS must parse without warnings');
}
assert.match(controls,/\.tabs,body\.nova \.cbi-tabmenu\{flex-wrap:nowrap;overflow-x:auto;overflow-y:hidden/);
assert.match(controls,/border-color:#7861df!important/,'Native focus border must match the theme');
assert.match(controls,/\.cbi-input-invalid:focus\{border-color:#d95772!important/,'Invalid input must remain visibly invalid');
assert.match(controls,/\.cbi-dynlist>\.item::after\{right:-1px;left:auto;width:32px/,'Native DynamicList has a physical-right remove hit test');
assert.doesNotMatch(controls,/\.cbi-dropdown\[open\]>ul\.dropdown\{[^}]*(?:top:|bottom:|left:|right:|max-height:)/,'LuCI must retain calculated dropdown geometry');
assert.doesNotMatch(controls,/display:none|appearance:none/,'Do not hide native controls, validation, or warnings');
assert.match(read('ucode/template/themes/nova/header.ut'),/controls\.css\?v=2\.3\.0-r1/,'New styles need a versioned runtime reference');
const source=read('htdocs/luci-static/resources/menu-nova-v260-r1.js');
const enhancement=read('htdocs/luci-static/nova/nova.js');
new Function(source);new Function(enhancement);
const persian=read('htdocs/luci-static/nova/persian.css');
assert.match(persian,/--font-sans:Estedad,Vazirmatn,sans-serif/,'Native font variables must not retain Helvetica');
assert.match(persian,/font-family:var\(--nova-font\)!important/,'Explicit legacy UI font declarations must be overridden');
assert.match(persian,/:not\(\.fa\)/,'Icon fonts must retain their own glyph face');
assert.match(persian,/body\.nova pre \*,body\.nova code \*/,'Raw logs/code must remain monospaced');
assert.match(read('ucode/template/themes/nova/header.ut'),/persian\.css\?v=2\.4\.0-r1/);
assert.doesNotMatch(read('ucode/template/themes/nova/header.ut'),/NETWORK OPERATIONS|NETWORK CONSOLE/,'Shell copy must use the native translation catalog');
function directionCase(lang,stored){
 const root={lang,dir:lang==='fa'?'rtl':'ltr',classList:{remove(){}}},callbacks={},keys=[];
 const button={attributes:{},setAttribute(key,value){this.attributes[key]=value;},addEventListener(event,callback){callbacks[event]=callback;}};
 vm.runInNewContext(enhancement,{document:{documentElement:root,getElementById:id=>id==='nova-direction'?button:null,querySelector:()=>null,addEventListener(){}},localStorage:{getItem:key=>{keys.push(key);return stored[key]??null;},setItem:(key,value)=>{stored[key]=value;}}});
 return {root,callbacks,keys,button};
}
const freshFa=directionCase('fa',{'nova-direction':'ltr'});
assert.equal(freshFa.root.dir,'rtl','A stale global English LTR preference must not override Persian');
freshFa.callbacks.click();assert.equal(freshFa.root.dir,'ltr','Direction toggle must remain functional');
assert.equal(directionCase('fa',{'nova-direction-fa':'ltr'}).root.dir,'ltr','Keep an explicit per-language user choice');
assert.equal(directionCase('en',{'nova-direction-fa':'rtl'}).root.dir,'ltr');
const freshEn=directionCase('en',{'nova-direction-en':'rtl','nova-direction':'rtl'});
assert.equal(freshEn.root.dir,'ltr','English must start LTR even after the legacy Persian demo');
assert.equal(freshEn.button.attributes['aria-pressed'],'false');
freshEn.callbacks.click();assert.equal(freshEn.root.dir,'rtl');assert.equal(freshEn.button.attributes['aria-pressed'],'true');
assert.equal(directionCase('en',{'nova-direction-en-v2':'rtl'}).root.dir,'rtl','A new deliberate manual layout choice persists');
assert.equal(directionCase('en-US',{'nova-direction-fa':'rtl'}).root.dir,'ltr');
assert.equal(directionCase('fa-IR',{}).root.dir,'rtl');
assert.equal(directionCase('ar',{}).root.dir,'rtl');
const languages=read('htdocs/luci-static/nova/languages.css');
assert.match(languages,/html\[lang\|=en\]\{--nova-font:system-ui/,'English must not be forced into the Persian face');
assert.match(languages,/html\[lang\|=en\] body\.nova\{--font-sans:var\(--nova-font\)/);
assert.match(languages,/html\[lang\|=en\]\[dir=ltr\][^\n]+text-align:left/,'English prose and field labels are left-aligned');
assert.match(languages,/margin-inline:8px 0/,'Submenu indentation mirrors with document direction');
assert.doesNotMatch(languages,/\.cbi-dynlist|\.cbi-dropdown\[/,'Language styling must not change native hit testing or geometry');
const header=read('ucode/template/themes/nova/header.ut');
assert.ok(header.indexOf('languages.css?v=2.6.0-r1')>header.indexOf('persian.css?v=2.4.0-r1'));
assert.match(header,/if \(rtl\):[^\n]+rel="preload"/,'Only RTL languages preload the Persian font');
assert.match(header,/nova-language-link[^\n]+admin\/system\/system/,'Language shortcut uses native LuCI settings, not another configuration API');
assert.match(read('root/etc/uci-defaults/90_luci-theme-nova'),/luci.languages.en='English'/);
assert.doesNotMatch(read('root/etc/uci-defaults/90_luci-theme-nova'),/luci.main.lang=/,'Package installation must not force a language');
const monitorSource=read('htdocs/luci-static/resources/nova-monitor-v270-r1.js');new Function(monitorSource);
assert.doesNotMatch(read('htdocs/luci-static/nova/visual.css'),/\.nova-chart-empty\{[^}]*direction:rtl/);
assert.match(monitorSource,/class:'nova-chart-empty',dir:fa\?'rtl':'ltr'/);
const monitor=vm.runInNewContext('(function(){'+monitorSource+'})()',{baseclass:{extend:o=>o}});
assert.deepEqual(JSON.parse(JSON.stringify(monitor.rates({rx:100,tx:200},{rx:400,tx:800},3))),{rx:800,tx:1600});
assert.equal(monitor.rates(null,{rx:400,tx:800},3),null,'The first counter is not a throughput sample');
assert.equal(monitor.rates({rx:100,tx:200},{rx:400,tx:800},0),null);
assert.equal(monitor.rates({rx:100,tx:200},{rx:400,tx:800},.01),null,'Near-simultaneous polling must not create huge false spikes');
assert.equal(monitor.rates({rx:100,tx:200},{rx:400,tx:800},30),null,'Background gaps must not produce misleading spikes');
assert.equal(monitor.rates({rx:100,tx:200},{rx:10,tx:800},3),null,'Counter reset must restart the baseline');
assert.equal(monitor.geometry([{rx:0},{rx:500},{rx:1000}],'rx',1000,720,210),'M0.00,210.00 L360.00,105.00 L720.00,0.00');
assert.equal(monitor.rates({rx:100,tx:200},{rx:NaN,tx:800},3),null);
assert.equal(monitor.rates({rx:100,tx:200},{rx:100,tx:800},NaN),null);
assert.equal(monitor.rates({rx:100,tx:200},{rx:Number.MAX_SAFE_INTEGER+1,tx:800},3),null,'Unsafe counters must not yield invented precision');
const points=monitor.coordinates([{time:0,rx:0},{time:3000,rx:500},{time:9000,rx:1000},{time:30000,rx:0}],'rx',1000,100,100,0,30000);
assert.deepEqual(JSON.parse(JSON.stringify(points.map(p=>p.x))),[0,10,30,100],'Time spacing must not use array indices');
assert.equal(monitor.paths(points,100).line,'M0.00,100.00 L10.00,50.00 L30.00,0.00 M100.00,100.00','Long gaps are separate segments');
assert.equal(monitor.paths(monitor.coordinates([{time:0,rx:100},{time:3000},{time:6000,rx:200}],'rx',1000,100,100,0,6000),100).line.match(/M/g).length,2,'A missing metric must break the series');
const weighted=monitor.statistics([{rx:100,tx:300,elapsed:3},{rx:300,tx:100,elapsed:9}]);
assert.equal(weighted.rx,250);assert.equal(weighted.tx,150);assert.equal(weighted.peakRx,300);
assert.equal(monitor.statistics([{time:3000,rx:100,tx:300,elapsed:3},{time:9000,rx:300,tx:100,elapsed:6}],2000,7000).rx,260,'Average clips measured intervals at the selected window edges');
const telemetry=read('htdocs/luci-static/nova/telemetry.css');
assert.match(telemetry,/prefers-reduced-motion:reduce/);assert.match(telemetry,/nova-motion-off \*\{animation:none!important;transition:none!important/);
assert.match(monitorSource,/poll.add\(update,3\)/,'Presentation motion must not increase RPC polling');
for(const weight of ['regular','medium','bold'])assert.equal(fs.readFileSync(path.join(root,'htdocs/luci-static/nova/estedad-'+weight+'.woff2')).subarray(0,4).toString(),'wOF2');
const technical=vm.runInNewContext('('+enhancement.match(/function technical\(value\)\{[^\n]+\}/)[0]+')');
assert.equal(technical('10.0.2.15/24'),true);
assert.equal(technical('fd4f:f17e:aeb2::1/60'),true);
assert.equal(technical('52:54:00:12:34:56'),true);
assert.equal(technical('آدرس 10.0.2.15'),false,'Persian labels must not be forced LTR');
assert.match(enhancement,/:scope > tbody > \.cbi-section-table-titles > th/,'Legacy Lua/PassWall headers must be enhanced');
assert.match(enhancement,/MutationObserver/,'Polling must preserve the new presentation');
assert.doesNotMatch(enhancement,/innerHTML\s*=|replaceChildren|replaceWith/,'Native controls and handlers must not be replaced');
assert.match(read('htdocs/luci-static/nova/components.css'),/\.left\{text-align:start!important\}/);
assert.match(read('htdocs/luci-static/nova/components.css'),/data-nova-label/);
function element(tag,attrs={},children=[]){return {tag,attrs,children:Array.isArray(children)?children:[children],style:{},appendChild(c){this.children.push(c)},setAttribute(k,v){this.attrs[k]=v},addEventListener(){}}}
const ids=Object.fromEntries(['topmenu','modemenu','nova-context','nova-page-title','tabmenu'].map(k=>[k,element('div')]));
const passwall={title:'PassWall 2',action:{type:'alias'},children:{settings:{title:'Basic Settings',children:{}},node_list:{title:'Node List',children:{}},node_subscribe:{title:'Node Subscribe',children:{}}}};
const tree={children:{admin:{title:'Administration',children:{services:{title:'Services',children:{passwall2:passwall}}}}}};
const context={document:{documentElement:{lang:'fa'},getElementById:id=>ids[id],createElementNS:(ns,t)=>element(t)},sessionStorage:{getItem(){return null}},E:element,_:s=>s,L:{env:{dispatchpath:['admin','services','passwall2','settings']},url:(...p)=>'/'+p.join('/')},baseclass:{extend:o=>o},ui:{menu:{getChildren(node){return Object.entries(node.children||{}).map(([name,n])=>({...n,name,...(n.action?.type==='alias'?{children:{}}:{})}))}}}};
const menu=vm.runInNewContext('(function(){'+source+'})()',context);
menu.render(tree);
assert.equal(ids.tabmenu.children[0].children.length,3,'Alias must retain all PassWall navigation tabs');
assert.equal(ids.tabmenu.children[0].children[0].attrs.class,'active');
assert.equal(ids.tabmenu.children[0].children[1].children[0].attrs.href,'/admin/services/passwall2/node_list');
const enIds=Object.fromEntries(Object.keys(ids).map(k=>[k,element('div')]));
const enContext={...context,document:{...context.document,documentElement:{lang:'en'},getElementById:id=>enIds[id]}};
vm.runInNewContext('(function(){'+source+'})()',enContext).render(tree);
assert.equal(enIds.tabmenu.children[0].children[2].children[0].children[0],'Subscriptions');
assert.equal(enIds['nova-context'].textContent,'Services / PassWall 2');
assert.equal(enIds.tabmenu.children[0].children[0].attrs.class,'active');
const lmo=fs.readFileSync(path.join(root,'root/usr/lib/lua/luci/i18n/nova.fa.lmo'));
const offset=lmo.readUInt32BE(lmo.length-4);assert.equal((lmo.length-4-offset)%16,0);
const dict=JSON.parse(read('src/fa.json'));
const fullCatalog=catalog();validateCatalog(fullCatalog);
assert.equal((lmo.length-4-offset)/16,1+fullCatalog.reduce((n,r)=>n+r.msgstr.length,0));
assert.equal(canonicalKey('  test\t text\n  '),'test text');
const translations=new Map();
for(let i=offset;i<lmo.length-4;i+=16)translations.set(lmo.readUInt32BE(i),lmo.subarray(lmo.readUInt32BE(i+8),lmo.readUInt32BE(i+8)+lmo.readUInt32BE(i+12)).toString());
for(const [key,value] of Object.entries(dict)){
 assert.equal(translations.get(sfh(canonicalKey(key))),value,'LMO lookup: '+key);
 assert.deepEqual((value.match(/%[sd]/g)||[]).sort(),(key.match(/%[sd]/g)||[]).sort(),'Formatting placeholders: '+key);
}
for(const row of fullCatalog)row.msgstr.forEach((value,i)=>assert.equal(translations.get(sfh(hashKey(row,i))),value,'Full catalog: '+row.msgid));
assert.equal(translations.get(0),'nplurals=2; plural=(n > 1);');
// Use the installed version's actual browser gettext functions, not another mock lookup.
const tr=Object.fromEntries([...translations].map(([key,value])=>[key.toString(16).padStart(8,'0'),value]));
const nativeContext={window:{TR:tr},TR:tr};vm.createContext(nativeContext);
vm.runInContext(read('scripts/fixtures/cbi-gettext.js'),nativeContext);
for(const row of fullCatalog)row.msgstr.forEach((value,i)=>{
 nativeContext.row=row;nativeContext.index=i;
 const result=vm.runInContext('row.msgid_plural ? N_(index ? 2 : 1,row.msgid,row.msgid_plural,row.msgctxt||undefined) : _(row.msgid,row.msgctxt||undefined)',nativeContext);
 assert.equal(result,value,'Native JS gettext: '+row.msgid);
});
// English is LuCI's source language: never load Persian entries or its plural rule.
const enLmo=fs.readFileSync(path.join(root,'root/usr/lib/lua/luci/i18n/nova.en.lmo'));
const enOffset=enLmo.readUInt32BE(enLmo.length-4);
assert.equal(enLmo.length-4-enOffset,16,'English catalog contains metadata only, not Persian strings');
assert.equal(enLmo.readUInt32BE(enOffset),0);
const enPlural=enLmo.subarray(enLmo.readUInt32BE(enOffset+8),enLmo.readUInt32BE(enOffset+8)+enLmo.readUInt32BE(enOffset+12)).toString();
assert.equal(enPlural,'nplurals=2; plural=(n != 1);');
const enTr={'00000000':enPlural};
const englishContext={window:{TR:enTr},TR:enTr};vm.createContext(englishContext);
vm.runInContext(read('scripts/fixtures/cbi-gettext.js'),englishContext);
let englishChecks=0;
for(const row of fullCatalog){
 englishContext.row=row;
 assert.equal(vm.runInContext('_(row.msgid,row.msgctxt||undefined)',englishContext),row.msgid);
 englishChecks++;
 if(row.msgid_plural)for(const count of [0,1,2,5]){
  englishContext.count=count;
  assert.equal(vm.runInContext('N_(count,row.msgid,row.msgid_plural,row.msgctxt||undefined)',englishContext),count===1?row.msgid:row.msgid_plural);
  englishChecks++;
 }
}
const rawLabels=read('htdocs/luci-static/nova/nova-i18n.js');new Function(rawLabels);
const englishGettext=s=>s,enLabelsContext={window:{_:englishGettext},document:{documentElement:{lang:'en'},addEventListener(){}}};
vm.runInNewContext(rawLabels,enLabelsContext);
assert.equal(enLabelsContext.window._,englishGettext,'Persian label compatibility layer must remain inactive in English');
assert.equal(enLabelsContext.window.novaLocalizeLabels,undefined);
const prefixContext={window:{_:s=>s==='Unable to load log data: '?'خطای گزارش: ':s},document:{documentElement:{lang:'fa'},addEventListener(){}}};
vm.runInNewContext(rawLabels,prefixContext);
assert.equal(prefixContext.window._('Unable to load log data: EIO'),'خطای گزارش: EIO');
assert.equal(prefixContext.window._('Unrelated error: EIO'),'Unrelated error: EIO');
assert.equal(prefixContext.window._('Unable to load log data: EIO','unrelated context'),'Unable to load log data: EIO');
const rawNode={nodeType:3,data:' Core '},inputNode={nodeType:1,value:'Core'};
prefixContext.window._=s=>s==='Core'?'هسته':s;
prefixContext.window.novaLocalizeLabels({querySelectorAll:()=>[{closest:()=>null,childNodes:[rawNode,inputNode]}]});
assert.equal(rawNode.data,' هسته ');assert.equal(inputNode.value,'Core','UI localization must not mutate input values');
for(const key of ['Network operations','Default DUID','Packet Steering','-- Please choose --','Pkts.'])assert.match(dict[key],/[\u0600-\u06ff]/);
assert.match(read('htdocs/luci-static/nova/cascade.css'),/html\[dir=rtl\]\.nova-menu-open/,'RTL mobile drawer must target root class');
await import('./test-languages.mjs');
await import('./test-firewall.mjs');
await import('./test-docs.mjs');
console.log('PASS: '+englishChecks+' English source/context/plural checks; bilingual direction, typography and navigation; full Persian gettext/LMO, eight CSS parses, native controls, firewall workspace, real-time coordinates/gaps and weighted rates');
